### ISSUE TITLE
Issue with tracking

### ISSUE THREAD

**Issue by TrueUO** [TrueUO/TrueUO#1034]

**Comment by TrueUO** [comment]
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Server.CSPRandom._GetBytes(Byte[] b, Int32 offset, Int32 count) in C:\Users\danrk\Desktop\Heritage\Server\Random.cs:line 195
   at Server.CSPRandom.NextDouble() in C:\Users\danrk\Desktop\Heritage\Server\Random.cs:line 237
   at Server.CSPRandom.Next(Int32 c) in C:\Users\danrk\Desktop\Heritage\Server\Random.cs:line 201
   at Server.SkillHandlers.TrackWhoGump.CheckDifficulty(Mobile from, Mobile m) in C:\Users\danrk\Desktop\Heritage\Scripts\Skills\Tracking.cs:line 494
   at Server.SkillHandlers.TrackWhoGump.<>c__DisplayClass13_0.<DisplayTo>b__4(Mobile m) in C:\Users\danrk\Desktop\Heritage\Scripts\Skills\Tracking.cs:line 284
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortQueryOperatorEnumerator`3.MoveNext(TInputOutput& currentElement, TSortKey& currentKey)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

at Server.SkillHandlers.TrackWhoGump.CheckDifficulty(Mobile from, Mobile m) in C:\Users\danrk\Desktop\Heritage\Scripts\Skills\Tracking.cs:line 494
https://github.com/TrueUO/TrueUO/blob/master/Scripts/Skills/Tracking.cs#L494

 at Server.SkillHandlers.TrackWhoGump.<>c__DisplayClass13_0.<DisplayTo>b__4(Mobile m) in C:\Users\danrk\Desktop\Heritage\Scripts\Skills\Tracking.cs:line 284
https://github.com/TrueUO/TrueUO/blob/master/Scripts/Skills/Tracking.cs#L284

**Comment by TrueUO** [comment]
return from.Skills[SkillName.Tracking].Fixed > Math.Min(m.Fame, 18000) / 1800 - 10 + Utility.Random(20);

this specifically.

**Comment by adverserath** [comment]
private void CheckSwap(int c)
		{
			lock (_sync)
			{
				if (_Index + c < BUFFER_SIZE)
				{
					return;
				}

				lock (_syncB)
				{
					byte[] b = _Working;
					_Working = _Buffer;
					_Buffer = b;
					_Index = 0;
				}
			}
			ThreadPool.QueueUserWorkItem(Fill);
		}

		private void _GetBytes(byte[] b, int offset, int count)
		{
            CheckSwap(count);
            lock (_sync)
			{
                Buffer.BlockCopy(_Working, _Index, b, offset, count);
				_Index += count;
			}
		}

Its interesting. In the code above there are multiple threads calling Utility.Random you end up with a racecondition in GetBytes.
This calls the CheckSwap method which rewrites the available bytes with a lock inside, when the lock closes the next thread is calling the CheckSwap again, before the first thread can get another lock on the Buffer.BlockCopy. So when the first thread does eventually lock for Buffer.BlockCopy the array size has changed, so we get the exception. 

My suggestion is to move CheckSwap calls inside the lock method to stop this happening. If you want to test this just do this anywhere in the code. You could still have the issue where one method is calling _GetBytes(byte[] b) and the other _GetBytes(byte[] b, int offset, int count)

`
            Parallel.For(0, 1000000, (i, loop) =>
            {
                Utility.Random(1, 20);
            });
`
