### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Argalep** [TrueUO/TrueUO#144]
https://github.com/TrueUO/TrueUO/blob/47fe71ec72f52593ccc42e1a07bf87015e509da7/Scripts/Services/LootGeneration/RunicReforging/RunicReforging.cs#L135

`Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Server.Items.RunicReforging.ApplyReforgedProperties(Item item, ReforgedPrefix prefix, ReforgedSuffix suffix, Int32 budget, Int32 perclow, Int32 perchigh, Int32 maxmods, Int32 luckchance, BaseRunicTool tool, ReforgingOption option) in ..\Scripts\Services\LootGeneration\RunicReforging\RunicReforging.cs:line 135
   at Server.Gumps.RunicReforgingGump.OnResponse(NetState state, RelayInfo info) in ..\Scripts\Services\LootGeneration\RunicReforging\Gumps.cs:line 366
   at Server.Network.PacketHandlers.DisplayGumpResponse(NetState state, PacketReader pvSrc) in ..\Server\Network\PacketHandlers.cs:line 1371
   at Server.Network.MessagePump.HandleReceive(NetState ns) in ..\Server\Network\MessagePump.cs:line 348
   at Server.Network.MessagePump.Slice() in ..\Server\Network\MessagePump.cs:line 136
   at Server.Core.Main(String[] args) in ..\Server\Main.cs:line 659 `

**Comment by kevin-10** [comment]
this should do it:

            var props = ItemPropertyInfo.LookupLootTable(item);

            if (props != null)
            {
                ApplyReforgedProperties(item, new List<int>(props), prefix, suffix, budget, perclow, perchigh, maxmods, luckchance, tool, option);
                ColUtility.Free(props);
            }
